### ISSUE TITLE
use wrapscan.io URIs

### ISSUE THREAD

**Issue by Niraj-Kamdar** [polywrap/wrap-abi-bindgen#61]
```yaml
  module: ./Cargo.toml
  schema: ./polywrap.graphql
  import_abis:
    - uri: wrap://ens/wraps.eth:abi-bindgen@0.1
```
update to wrapscan.io
